---
platform: linux

image: docker:///java#8

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: pcf-demo
  
outputs:
  - name: build

run:
  path: pcf-demo/ci/tasks/build.sh
  args: [
    --input-dir, pcf-demo,
    --output-dir, build,
  ]
