---
resources:
  - name: pcf-demo
    type: git
    source:
      uri: https://github.com/mmcvay-pivotal/PCF-demo.git
      branch: master
 
  - name: candidate-release
    type: git
    source:
      uri: https://github.com/mmcvay-pivotal/PCF-demo-candidate-release.git
      branch: master
 
  - name: cf
    type: cf
    source:
      api: https://api.local.pcfdev.io
      username: admin   
      password: admin
      organization: pcfdev-org
      space: pcfdev-space
      skip_cert_check: true

jobs:
  - name: unit-test
    public: true
    plan:
      - get: pcf-demo
        trigger: true
      - task: unit
        file: pcf-demo/ci/tasks/unit.yml
        

  - name: build-artifact-to-candidate-release
    serial_groups: [ version ]
    plan:
      - get: pcf-demo
        passed: [ unit-test ]
        trigger: true
      - task: build
        file: pcf-demo/ci/tasks/build.yml
      - put: candidate-release
        params: { from: build/pcf-demo.war }
 

  